---
Name: swagger-devtool
---
Silverstripe\Swagger\SwaggerController:
  swagger_json_path: 'silverstripe/swagger-ui: /client/swagger.json'
SilverStripe\Dev\DevelopmentAdmin:
  registered_controllers:
    swagger:
      controller: 'Silverstripe\Swagger\SwaggerController'
